### ISSUE TITLE
PRACTICA 5 DISEÑO DE CONTROL PERSONALIZADO

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Litzy-lopez4#2]
[PRACTICA 5.zip](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Litzy-lopez4/files/8337712/PRACTICA.5.zip)
[Practica 5 Diseño de control personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Litzy-lopez4/files/8337713/Practica.5.Diseno.de.control.personalizado.pdf)

**Comment by magaly1311** [comment]
Calificación de la práctica 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
